// interface ConfigType {
//     fileList: fileListNames,
//     useSR: useSR.value,
//     SRMethodValue: SRMethodValue.value,
//     RealcuganTileValue: RealcuganTileValue.value,
//     RealcuganInferenceValue: RealcuganInferenceValue.value,
//     RealcuganModelValue: RealcuganModelValue.value,
//     RealcuganAlphaValue: RealcuganAlphaValue.value,
//     RealesrganInferenceValue: RealesrganInferenceValue.value,
//     RealesrganModelValue: RealesrganModelValue.value,
//     RealesrganTileValue: RealesrganTileValue.value,
//     RealesrganScaleValue: RealesrganScaleValue.value,
//     // ArtCNNInferenceValue: ArtCNNInferenceValue.value,
//     // ArtCNNModelValue: ArtCNNModelValue.value,
//     // ArtCNNTileValue: ArtCNNTileValue.value,
//     Waifu2xInferenceValue: Waifu2xInferenceValue.value,
//     Waifu2xModelValue: Waifu2xModelValue.value,
//     Waifu2xTileValue: Waifu2xTileValue.value,
//     SwinIRInferenceValue: SwinIRInferenceValue.value,
//     SwinIRModelValue: SwinIRModelValue.value,
//     SwinIRTileValue: SwinIRTileValue.value,
//     SR_ExtraModelValue: SR_ExtraModelValue.value,
//     SR_ExtraModelInferenceValue: SR_ExtraModelInferenceValue.value,
//     Sr_numstreams: Sr_numstreams.value,
//     Sr_cudagraph: Sr_cudagraph.value,
//
//     useVfi: useVfi.value,
//     VfiMethodValue: VfiMethodValue.value,
//     RifeInferenceValue: RifeInferenceValue.value,
//     RifeModelValue: RifeModelValue.value,
//     RifeScaleValue: RifeScaleValue.value,
//     RifeMultiValue: RifeMultiValue.value,
//     RifeEnsembleValue: RifeEnsembleValue.value,
//     RifeDetectionValue: RifeDetectionValue.value,
//     Vfi_numstreams: Vfi_numstreams.value,
//     Vfi_cudagraph: Vfi_cudagraph.value,
//
//     UseResize_BeforeEnhance: UseResize_BeforeEnhance.value,
//     UseResize_AfterEnhance: UseResize_AfterEnhance.value,
//     ResizeWidth_BeforeEnhance: ResizeWidth_BeforeEnhance.value,
//     ResizeHeight_BeforeEnhance: ResizeHeight_BeforeEnhance.value,
//     ResizeWidth_AfterEnhance: ResizeWidth_AfterEnhance.value,
//     ResizeHeight_AfterEnhance: ResizeHeight_AfterEnhance.value,
//     ReduceLeft_BeforeEnhance: ReduceLeft_BeforeEnhance.value,
//     ReduceRight_BeforeEnhance: ReduceRight_BeforeEnhance.value,
//     ReduceOn_BeforeEnhance: ReduceOn_BeforeEnhance.value,
//     ReduceDown_BeforeEnhance: ReduceDown_BeforeEnhance.value,
//     ReduceLeft_AfterEnhance: ReduceLeft_AfterEnhance.value,
//     ReduceRight_AfterEnhance: ReduceRight_AfterEnhance.value,
//     ReduceOn_AfterEnhance: ReduceOn_AfterEnhance.value,
//     ReduceDown_AfterEnhance: ReduceDown_AfterEnhance.value,
//
//     bitValue: bitValue.value,
//     crfValue: crfValue.value,
//     encoderValue: encoderValue.value,
//     qualityValue: qualityValue.value,
//     videoContainer: videoContainer.value,
//     AudioContainer: AudioContainer.value,
//     isUseCrf: isUseCrf.value,
//     isSaveAudio: isSaveAudio.value,
//     isSavesubtitle: isSavesubtitle.value,
//     outputfolder: outputfolder.value,
// }
